apiVersion: v1
kind: Service
metadata:
  name: kubia-frontend
spec:
  selector:
    app: kubia-frontend
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: https
    port: 443
    targetPort: 8081
  selector:
   app: kubia-deployment
